import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {

  const [todos, settodos] = useState([]);
  
  const fetchTodos = async () => {
    const response = await fetch("/api/todos");
    const data = await response.json();
    settodos(data);
  };
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={fetchTodos}>Get todos</button>        
        <ul>
          {todos.map((todo) => {
            return (
              <li
                style={{ color: `${todo.completed ? "green" : "red"}` }}
                key={todo.id}
              >
                    {todo.todo}:{todo.completed}. 
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}
